_BATCH_ACCOUNT_NAME ='' # Your batch account name 
_BATCH_ACCOUNT_KEY = '' # Your batch account key
_BATCH_ACCOUNT_URL = '' # Your batch account URL
_STORAGE_ACCOUNT_NAME = '' # Your storage account name
_STORAGE_ACCOUNT_KEY = '' # Your storage account key
_POOL_ID = 'PythonQuickstartPool' # Your Pool ID
_POOL_NODE_COUNT = 2 # Pool node count
_POOL_VM_SIZE = 'STANDARD_A1_v2' # VM Type/Size
_JOB_ID = 'PythonQuickstartJob' # Job ID
_STANDARD_OUT_FILE_NAME = 'stdout.txt' # Standard Output file